### PR TITLE
Allow Setting Pinning Cookie Attributes

### PR DESCRIPTION
**Pull request by dchukhin**
This pull request allows users to set the pinning cookie's 'Secure', 'HttpOnly', and 'SameSite' attributes by using settings, which are based on Django's `CSRF_COOKIE_SECURE`, `CSRF_COOKIE_HTTPONLY`, and `CSRF_COOKIE_SAMESITE` settings.
The defaults for these settings keep the current behavior: not Secure, not HttpOnly, and 'Lax' SameSite (currently, the SameSite attribute is unset, which [should default to 'Lax' in browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)).

A part of this work also changes the `PINNING_COOKIE` and `PINNING_SECONDS` in `multidb/middleware.py` to be functions, so they can be tested more easily.

### CODE REVIEW

**Comment by tobiasmcnulty** [comment]
Hey @jbalogh, hope you are well! I just wanted to check to see if this change is something you would consider accepting at some point. (Full disclosure, @dchukhin is on my team at Caktus). We're happy to help in any way with merge and/or release. Thanks as always for the numerous Django packages we seem to find handy! 🙂

**Comment by Jdsleppy** [comment]
Hi @diox , I think these changes are what you were looking for.  GitHub says you need to manually approve running CI on this PR because it's from a first-time contributor to this repository.  Cheers!

**Review by diox — APPROVED** [review]
Awesome, thanks for doing this

**Comment by diox** [comment]
0.10 has been released with this change.

**Pull request merged**
